# Generated by Django 5.2.6 on 2025-09-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0003_remove_course_teachers_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Learn.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(),
        ),
    ]
