# Generated by Django 5.2.6 on 2025-09-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0004_alter_subject_course_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='Learn.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
