# Generated by Django 5.2.6 on 2025-09-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0005_curriculum_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
